// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2203.202 at 11:50 AM on Monday, December 5, 2022.
	/// </remarks>
	public partial class Model5_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vbool48'</summary>
		public Bernoulli vbool48_marginal_F;
		/// <summary>Message to marginal of 'vbool49'</summary>
		public Bernoulli vbool49_marginal_F;
		/// <summary>Message to marginal of 'vbool50'</summary>
		public Bernoulli vbool50_marginal_F;
		/// <summary>Message to marginal of 'vbool51'</summary>
		public Bernoulli vbool51_marginal_F;
		/// <summary>Message to marginal of 'vbool52'</summary>
		public Bernoulli vbool52_marginal_F;
		/// <summary>Message to marginal of 'vbool53'</summary>
		public Bernoulli vbool53_marginal_F;
		/// <summary>Message to marginal of 'vbool54'</summary>
		public Bernoulli vbool54_marginal_F;
		/// <summary>Message to marginal of 'vbool55'</summary>
		public Bernoulli vbool55_marginal_F;
		/// <summary>Message to marginal of 'vbool56'</summary>
		public Bernoulli vbool56_marginal_F;
		/// <summary>Message to marginal of 'vbool57'</summary>
		public Bernoulli vbool57_marginal_F;
		/// <summary>Message to marginal of 'vbool58'</summary>
		public Bernoulli vbool58_marginal_F;
		/// <summary>Message to marginal of 'vbool59'</summary>
		public Bernoulli vbool59_marginal_F;
		/// <summary>Message to marginal of 'vbool60'</summary>
		public Bernoulli vbool60_marginal_F;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			Bernoulli vBernoulli33 = Bernoulli.FromLogOdds(double.NegativeInfinity);
			this.vbool48_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool48_use_B = Bernoulli.Uniform();
			// Message to 'vbool48_marginal' from Variable factor
			this.vbool48_marginal_F = VariableOp.MarginalAverageConditional<Bernoulli>(vbool48_use_B, vBernoulli33, this.vbool48_marginal_F);
			Bernoulli vBernoulli34 = Bernoulli.Uniform();
			this.vbool49_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool50_F = default(Bernoulli);
			this.vbool50_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool50_use_B = Bernoulli.Uniform();
			// Message to 'vbool50' from Or factor
			vbool50_F = BooleanOrOp.OrAverageConditional(vBernoulli33, vBernoulli34);
			// Message to 'vbool50_marginal' from DerivedVariable factor
			this.vbool50_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool50_use_B, vbool50_F, this.vbool50_marginal_F);
			this.vbool51_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool52_F = default(Bernoulli);
			this.vbool52_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool52_use_B = Bernoulli.Uniform();
			// Message to 'vbool52' from Or factor
			vbool52_F = BooleanOrOp.OrAverageConditional(vbool50_F, vBernoulli34);
			// Message to 'vbool52_marginal' from DerivedVariable factor
			this.vbool52_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool52_use_B, vbool52_F, this.vbool52_marginal_F);
			this.vbool53_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool54_F = default(Bernoulli);
			this.vbool54_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool54_use_B = Bernoulli.Uniform();
			// Message to 'vbool54' from Or factor
			vbool54_F = BooleanOrOp.OrAverageConditional(vbool52_F, vBernoulli34);
			// Message to 'vbool54_marginal' from DerivedVariable factor
			this.vbool54_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool54_use_B, vbool54_F, this.vbool54_marginal_F);
			this.vbool55_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool56_F = default(Bernoulli);
			this.vbool56_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool56_use_B = Bernoulli.Uniform();
			// Message to 'vbool56' from Or factor
			vbool56_F = BooleanOrOp.OrAverageConditional(vbool54_F, vBernoulli34);
			// Message to 'vbool56_marginal' from DerivedVariable factor
			this.vbool56_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool56_use_B, vbool56_F, this.vbool56_marginal_F);
			this.vbool57_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool58_F = default(Bernoulli);
			this.vbool58_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool58_use_B = Bernoulli.Uniform();
			// Message to 'vbool58' from Or factor
			vbool58_F = BooleanOrOp.OrAverageConditional(vbool56_F, vBernoulli34);
			// Message to 'vbool58_marginal' from DerivedVariable factor
			this.vbool58_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool58_use_B, vbool58_F, this.vbool58_marginal_F);
			this.vbool59_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool60_F = default(Bernoulli);
			this.vbool60_marginal_F = Bernoulli.Uniform();
			Bernoulli vbool60_use_B = Bernoulli.Uniform();
			// Message to 'vbool60' from Or factor
			vbool60_F = BooleanOrOp.OrAverageConditional(vbool58_F, vBernoulli34);
			// Message to 'vbool60_marginal' from DerivedVariable factor
			this.vbool60_marginal_F = DerivedVariableOp.MarginalAverageConditional<Bernoulli>(vbool60_use_B, vbool60_F, this.vbool60_marginal_F);
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			this.Constant();
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vbool48") {
				return this.Vbool48Marginal();
			}
			if (variableName=="vbool49") {
				return this.Vbool49Marginal();
			}
			if (variableName=="vbool50") {
				return this.Vbool50Marginal();
			}
			if (variableName=="vbool51") {
				return this.Vbool51Marginal();
			}
			if (variableName=="vbool52") {
				return this.Vbool52Marginal();
			}
			if (variableName=="vbool53") {
				return this.Vbool53Marginal();
			}
			if (variableName=="vbool54") {
				return this.Vbool54Marginal();
			}
			if (variableName=="vbool55") {
				return this.Vbool55Marginal();
			}
			if (variableName=="vbool56") {
				return this.Vbool56Marginal();
			}
			if (variableName=="vbool57") {
				return this.Vbool57Marginal();
			}
			if (variableName=="vbool58") {
				return this.Vbool58Marginal();
			}
			if (variableName=="vbool59") {
				return this.Vbool59Marginal();
			}
			if (variableName=="vbool60") {
				return this.Vbool60Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool48' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool48Marginal()
		{
			return this.vbool48_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool49' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool49Marginal()
		{
			return this.vbool49_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool50' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool50Marginal()
		{
			return this.vbool50_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool51' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool51Marginal()
		{
			return this.vbool51_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool52' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool52Marginal()
		{
			return this.vbool52_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool53' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool53Marginal()
		{
			return this.vbool53_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool54' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool54Marginal()
		{
			return this.vbool54_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool55' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool55Marginal()
		{
			return this.vbool55_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool56' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool56Marginal()
		{
			return this.vbool56_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool57' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool57Marginal()
		{
			return this.vbool57_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool58' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool58Marginal()
		{
			return this.vbool58_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool59' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool59Marginal()
		{
			return this.vbool59_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool60' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool60Marginal()
		{
			return this.vbool60_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
